.eslintrc.json, tailwind.config.ts
> ST-1-ts.config-setting
> ts.config 기초적인 셋팅만 추가했습니다. 
> 내용만 확인해주세요
=> chore: ST-1-ts.config-setting

.husky/commit-msg, .husky/pre-commit, .husky/pre-push, .husky/prepare-commit-msg
> St 3 husky
> commit 시 메세지 맞춤 설정, 린트 설정확인
> commit 시 티켓번호 자동 발행
> push 시 build 테스트
=> chore: ST-3-husky

.prettierrc.js, package-lock.json, package.json, pnpm-lock.yaml, tailwind.config.ts
tailwind.config랑 .prettierrc.js 파일 수정했습니다.
=> chore: St 7 palette 테일윈드 palette 추가, 프리티어 import 자동정렬 plugin 추가

src/app/page.tsx, tailwind.config.ts
승헌님이 안건 내주신걸로 수정했고, 잘 적용되는 것까지 확인했습니다.
=> chore: ST-17 브레이크 포인트 수정

.github/workflows/check-test-folder.yml
저가요 테스트 폴더가 존재하는지 체크해서 없다면 PR을 merge할 수 없는 깃허브 액션을 만들었걸랑요
근데 잘 작동하는지 보려면 이 PR이 통과되어야 합니다
빠승(빠른 승인) 부탁.
가능하다면 교차 검증도 부탁드려요
=> chore: test 폴더 체크하는 상태 검사 추가

.husky/pre-commit, next.config.mjs
> St-50-feat-NextConfig-domain
> domain에 추가했습니다!
> api에서 불러온 이미지를 렌더링 할 수 있도록 빠른 어프로브 부탁드립니다! 2번째 어프로브 주신 분이 머지하셔도 돼요!
=> feat: nextconfig domain(ST-50)

src/apis/API.type.ts, src/apis/activitiesAPI.ts, src/apis/myNotificationsAPI.ts, src/apis/myReservationAPI.ts
> ST-51-refactor-api
> 단일인자만 받는 api는굳이 params로 하는거에서 불편을 느낀다해서 그렇게 생각해서 수정했습니다.
> 빠른 머지 부탁드릴게요
=> refactor: 단일값 받는 파일 params 제거(ST-51)

package.json, pnpm-lock.yaml, public/icons/icon-meatball.svg, public/icons/icon-next.svg, public/icons/icon-prev.svg, src/app/[activityId]/_components/ActivityIdDetail.tsx, src/app/[activityId]/_components/Map.tsx, src/app/_components/Header.tsx, src/contexts/ReactQueryProviders.tsx
> St-57-ActivityPage-ActivityIdDetail
> 반응형 별 마진 값 제외하고 전부 구현했고, 천천히 구현하겠습니다.
> 별 거 없지만 한 번 살펴봐주세요!
=> faet: ActivityID페이지의 ActivityDetail 컴포넌트 구현 (St-57)

src/apis/API.type.ts
> ST-73
> api type 들을 좀더 자세히 작성해서 수정했습니다. 
> @heony704 @JustDevRae @hnitam @PixeIDark
=> refactor: api type 세분화(ST-73)

src/apis/OauthAPI.ts, src/apis/authAPI.ts, src/app/_components/Header.tsx, src/store/socialLoginStore.ts
> ST-93
> 로그인시 상태값 받아서 소셜인지 아닌지 판단하고 유저데이터를 담아 쿠키로 저장하는 작업 
> 상태값 맨 아래 사진처럼 객체로 보관해서 쿠키로 보내줍니다
=> feat: 로그인시 상태값 받아 쿠키에저장(ST-93)

src/app/(user)/layout.tsx
> ST-98
> 마이 페이지 자식요소들 색 gray-300 -> gray-100 변경
> 토큰이 있는지 확인 클라이언트 -> 서버로 변경 
> 빠승 부탁드려요
=> hotfix: mypage layout(ST-98)

src/components/Modal.tsx
> ST-100
> 스크럼 안건대로 수정했고, 추가로 font가 적용안되서 바꿨습니다.
=> style: 모달 높이 자유롭게, 너비 460, font크기 수정(ST-100)

src/components/Popup.tsx
> ST-102
> 스크럼 안건대로 오른쪽 버튼이 파랗게 빛나게했습니다!
=> style: 오른쪽 버튼이 파랗게 빛나게 수정(ST-102)

src/app/(user)/myactivities/_components/MyActivities.tsx
=> fix: 등록 url 수정(ST-110)

src/app/_components/Header/UserExist.tsx, src/app/_components/Header/UserPopover.tsx, src/app/_components/Header/index.tsx
> ST-144
> - 로딩 상태를 만들어서 userInfo가 로딩중에는 아무것도 안보이게 만들었습니다.
> - UserDropdown의 이름을 UserPopover로 변경했습니다. 쓰이는 컴포넌트들이 Popover라 이게 더 적절해보였어요.
=> fix: 헤더가 로딩 중일 때는 로그인, 로그아웃 안보이게 수정(ST-144)

src/app/(auth)/layout.tsx, src/app/(user)/layout.tsx, src/app/(user)/reservation-status/page.tsx, src/components/Modal.tsx, src/middleware.ts
> ST-161
> 기존 auth, user layout에서 accessToken을 기반으로 사용자 리다이렉트를 시켜주는 로직을 삭제하고 next의 middleware를 만들어서 처리해줬습니다.. 근데 middleware에서 그룹핑된 폴더 경로를 인식하지 못해서 좀 더럽게 썻어요..
=> feat: 미들웨어 추가 빌드 오류 해결 모달 아이콘 수정(ST-161)

src/app/(home)/[activityId]/_components/Review/ReviewDetail.tsx, src/app/(home)/[activityId]/_hooks/useGetCommentReviewViewModel.ts, src/app/(home)/[activityId]/_utils/getCommentData.ts
> ST-162
> 기존에는 정수로만 떳는데 소수점 첫번째 자리까지는 뜨게해줌.
=> refactor: 후기 별점 소수점 첫번째자리까지 뜨게함(ST-162)

src/app/(home)/[activityId]/_components/ReservationSteps/Calendar/CalendarDay.tsx, src/app/(home)/[activityId]/_utils/createCalendar.ts
> ST-164
> 지난 날짜는 예약에 안 뜨게 더 엄격히 검사
=> fix: 지난 날짜는 예약에 안 뜨게 더 엄격히 검사(ST-164)

src/app/_components/Notification/index.tsx
> ST-166
> 알람이 존재하지 않을때 빨간점 안뜨게
=> fix: notificationData 수정(ST-166)

src/app/(home)/search/_components/SortDropdown.tsx
> ST-170
> 검색페이지에서 뭐 솔트 고르고 새로고침해도 한글로 잘뜹니다.
=> fix: sort 새로고침해도 잘뜸(ST-170)

src/apis/OauthAPI.ts, src/apis/authAPI.ts
> ST-174
> readOnly는 백엔드 단에서 할 수 있고 클라이언트단 에서는 불가능 하다고 합니다.
> sameSite, secure를 추가해서 보안을 올렸습니다. 
=> fix: 토큰에 sameSite, secure추가(ST-174)

src/components/Popup.tsx
> ST-176
> 그냥 모달꺼 복붙해서 모달처럼 스크롤 안먹게 수정 했습니다. 
=> fix: 모달처럼 스크롤 안먹게 수정 팝업도(ST-176)

src/app/_components/Notification/index.tsx
> ST-177
> 알람버튼 눌렀을대 mousedown 이벤트에서 1회 click에서 이벤트 1회 일어나던 것 1회만 일어나게 했습니다.
=> fix: notification 오픈 상태 2회 바뀌는 것 수정(ST-177)

package.json, pnpm-lock.yaml, src/app/(user)/myactivities/add/_components/Add.tsx, src/app/(user)/myactivities/edit/_components/Edit.tsx
> ST-165
> - 체험 등록 수정 시 메인페이지에 반영 안되는 문제
> - 등록버튼 sub이미지도 넣어야 빛나게 수정
> - Sharp 라이브러리 추가
=> refactor: 체험 등록 수정 페이지 메인페이지 반영

src/app/(home)/[activityId]/_components/Images.tsx, src/app/(home)/[activityId]/page.tsx
> ex) ST-172
>- 옛날 코드 참고해서 만들었습니다. 주로 w-full을 w-screen으로 바꾸니까 잘 동작하네요
>- mx-[0.5px]이 의아해하실수 있는데 tablet 이상사이즈에서 -mx-6을 없애기 위해 넣었습니다. mx-0, -mx-0, mx-auto 이친구들로는 적용이 안돼요
https://github.com/user-attachments/assets/f3b7e4a2-1bda-46d2-a36b-e618fc16b2a8
> 매우 엄격하게 이미지가 1개일 때랑 여러 개일 때랑 반응형 해서 평가해주시면 좋겠습니다. 그리고 이미지가 1개 일 때 기준 타블릿 사이즈에서 살짝 확대? 하는 느낌이 있어요
=> style: activity page css 수정

src/app/(user)/myactivities/_components/MyActivities.tsx, src/app/(user)/myactivities/add/_components/Add.tsx, src/app/(user)/myactivities/edit/_components/Edit.tsx, src/app/(user)/reservations/_components/MyReservations.tsx
- ST-178
그냥 글씨 여백이랑 체험 등록/수정 페이지 살짝 바꿨습니다.
=> style: 체험 등록/수정 페이지 스타일 수정 (ST-178)

src/app/(user)/myactivities/add/_components/Add.tsx, src/app/(user)/myactivities/add/_components/NumberInput.tsx, src/app/(user)/myactivities/edit/_components/Edit.tsx
> ST-169
가격 입력시 , 넣기 그리고 가격 위아래 버튼 없애기
동작이 되었다가 안되었다가 합니다...
=> refactor: 체험 등록 수정 페이지 가격 input

src/app/(user)/myactivities/add/_components/Add.tsx, src/app/(user)/myactivities/edit/_components/Edit.tsx
> ST-181
> 날짜 입력 시 하루전으로 표시되는 오류 수정했습니다.
=> fix: 체험 등록 수정 페이지 날짜오류수정
